version: "3.7"
services:
  server:
    build:
      context: .
    container_name: server
    image: server:local
    deploy:
      resources:
          limits:
            cpus: '1'
            memory: 512MB
    networks:
      - fibonacci-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SERVER_ADDR: http://localhost:8080
      SERVER_PORT: ":8080"
      LOG_LEVEL: info
      DATABASE_CONFIG: host=postgres user=fibonacci-api password=fibonacci-api dbname=fibonacci-api port=5432 sslmode=disable TimeZone=America/Chicago


  postgres:
    container_name: postgres
    image: postgres:14.2
    command:  postgres -c 'max_connections=250'
    networks:
      - fibonacci-api
    environment:
      POSTGRES_USER: fibonacci-api
      POSTGRES_DB: fibonacci-api
      POSTGRES_PASSWORD: fibonacci-api
      PGGSSENCMODE: disable
    ports:
      - "5432:5432"

networks:
  fibonacci-api: